---
- name: Install andrewrothstein.sudoers
  ansible.buildint.include_role:
    name: andrewrothstein.sudoers
- name: Install andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Install andrewrothstein.gpg
  ansible.builtin.include_role:
    name: andrewrothstein.gpg
- name: Install andrewrothstein.matchbox
  ansible.builtin.include_role:
    name: andrewrothstein.matchbox

- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Create matchbox service account
  ansible.builtin.include_role:
    name: andrewrothstein.service_account
  vars:
    service_account:
      user:
        name: '{{ matchbox_config_user | default("matchbox") }}'
        group: '{{ matchbox_config_group | default("matchbox") }}'
      directories:
        - d: '{{ matchbox_config_data_path }}'
        - d: '{{ matchbox_config_assets_path }}'
        - d: '{{ matchbox_config_etc }}'
      tls:
        pki_dir: '{{ matchbox_config_tls.pki_dir }}'
        dest_dir: '{{ matchbox_config_etc }}'
    tls_dest_file_names:
      ca: ca.crt
      cert: server.crt
      key: server.key

- name: Configuring for {{ matchbox_supervisor | default("systemd") }}
  ansible.builtin.include_tasks: '{{ matchbox_supervisor | default("systemd") }}.yml'

- name: Install fedora coreos kernel binary assets
  become: true
  become_user: '{{ matchbox_config_user }}'
  with_items: '{{ matchbox_config_get_coreos | default([]) }}'
  ansible.builtin.command: >-
    {{ matchbox_config_get_coreos_bin }}
    {{ item.channel }}
    {{ item.version }}
    {{ matchbox_config_assets_path -}}
  args:
    creates: '{{ matchbox_config_assets_path }}/fedora-coreos/fedora-coreos-{{ item.version }}-metal.x86_64.raw.xz'

- name: Install flatcar kernel binary assets
  become: true
  become_user: '{{ matchbox_config_user }}'
  with_items: '{{ matchbox_config_get_flatcar | default([]) }}'
  ansible.builtin.command: >-
    {{ matchbox_config_get_flatcar_bin }}
    {{ item.channel }}
    {{ item.version }}
    {{ matchbox_config_assets_path -}}
  args:
    creates: '{{ matchbox_config_assets_path }}/flatcar/{{ item.version }}/flatcar_production_pxe_image.cpio.gz'
