---
- name: andrewrothstein.sudoers
  version: v1.1.0
- name: andrewrothstein.curl
  version: v1.0.18
- name: andrewrothstein.gpg
  version: v1.0.14
- name: andrewrothstein.matchbox
  version: v2.1.1
- name: andrewrothstein.systemd_service
  version: v3.1.1
- name: andrewrothstein.service_account
  version: v0.1.0
