---
- name: andrewrothstein.sudoers
  version: v1.2.2
- name: andrewrothstein.curl
  version: v1.1.0
- name: andrewrothstein.gpg
  version: v1.2.3
- name: andrewrothstein.matchbox
  version: v2.1.4
- name: andrewrothstein.systemd_service
  version: v3.2.2
- name: andrewrothstein.service_account
  version: v1.0.0
